### ISSUE TITLE
Add OpenSRP Apache 2 Licence

### ISSUE THREAD

**Issue by ndegwamartin** [OpenSRP/opensrp-client-fp#1]
- [x] Add license
- [x] Add change log

**Comment by cafootitt** [comment]
@ndegwamartin Hi Martin - is this finished and can I close this? If not, can you assign someone (or yourself) to complete this, now that we're doing active development on this repo?

**Comment by ndegwamartin** [comment]
Yeah these can be closed

**Comment by cafootitt** [comment]
https://github.com/OpenSRP/opensrp-client-fp/blob/master/LICENSE and https://github.com/OpenSRP/opensrp-client-fp/blob/master/CHANGELOG.md
