### ISSUE TITLE
Implement the client's profile dropdown menu

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-fp#14]
Marvel handoff: https://marvelapp.com/9c67ab6/screen/64579366/handoff

- [x] This menu opens when the user taps on the 3 dots 
- [x] It closes if the user taps anywhere outside the menu
- [x] The call option launches the device's phone app and pastes in the client's phone number (this comes from the `tel_number` field in the registration form).
- [x] Start visit option opens a new, blank FP visit form for that client
- [x] Close FP record option opens the close FP record form #10

**Comment by dubdabasoduba** [comment]
Can be copy pasted directly from ANC we only change the for form on the close action to the close_fp form and the start anc visit/contact functionality to start the family planning visit functionality.

**Comment by cafootitt** [comment]
QA 29 April build: lgtm, good work!
