### ISSUE TITLE
Create client profile page - History tab

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-fp#15]
Marvel handoff: https://marvelapp.com/9c67ab6/screen/62597829/handoff

- [x] The history tab lists all submitted FP visits, in reverse chronological order (most recent on top), based on the `visit_date` in the FP visit form.
- [x] The date of the visit is displayed in DD MMM YYYY format.
- [x] The method displayed is the `method_exit` from the Service Provision section of the FP visit form.
- [x] Tapping on the row takes the user to the full, view-only FP visit form that was previously submitted.

**Comment by dubdabasoduba** [comment]
Large because you have to do the design and chronological ordering of all fetched data. The open and pre-populate a form and make it un-editable

**Comment by cafootitt** [comment]
QA 14 May release - lgtm, good work!
