### ISSUE TITLE
Implement follow-up visit buttons on the main register page

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-fp#17]
Marvel handoff: https://marvelapp.com/9c67ab6/screen/67385096/handoff

Referring to the schedules, https://github.com/OpenSRP/opensrp-client-fp/issues/16, create buttons on the main register page, so that the health worker knows when follow-up visits are due.

- [x] Blue button "FOLLOWUP DUE" should display when the client has a service schedule that is currently in the DUE period.
- [x] Red button "FOLLOWUP OVERDUE" should display when the client has a service schedule that is currently in the OVERDUE period.
- [x] Grey text "FOLLOWUP DD MMM YYYY" should display when the client has a service schedule that is scheduled but not yet DUE. 
- [x] Blue and red buttons open a new, blank FP visit form for that client.
- [x] The grey text is not a button and nothing should happen when you tap on it.

**Comment by dubdabasoduba** [comment]
The same schedules rules in #16 can be used here.

**Comment by cafootitt** [comment]
June 9th QA - lgtm
