### ISSUE TITLE
Implement follow-up visit buttons on the client profile page

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-fp#18]
Marvel handoff: https://marvelapp.com/9c67ab6/screen/64579367/handoff

Similar to https://github.com/OpenSRP/opensrp-client-fp/issues/17, we will add the followup visit buttons on the client's profile page.

- [x] Blue button shows DD MMM YYYY of the due date of the visit; tapping on the button opens a new, blank FP visit form
- [x] Red button (not pictured) shows DD MMM YYYY of the original due date of the visit; tapping on the button opens a new, blank FP visit form
- [x] Grey text (not pictured) shows DD MMM YYYY of the upcoming due date of the visit; nothing happens when the user taps on the button

**Comment by dubdabasoduba** [comment]
Should use the same functionality used in #17 so the only change it to make sure the design fits well

**Comment by cafootitt** [comment]
QA 14 May release:

- [x] The Grey button's text should also be grey instead of blue (see below).
![Screenshot_20200515-120352_Family Planning](https://user-images.githubusercontent.com/3488986/82043919-513d5b80-96a4-11ea-9ec2-7a752154a3ec.jpg)

**Comment by cafootitt** [comment]
QA June 9th - lgtm
