### ISSUE TITLE
Implement the FP visit form

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-fp#19]
Marvel handoffs:
https://marvelapp.com/9c67ab6/screen/67327969/handoff
https://marvelapp.com/9c67ab6/screen/64579368/handoff
https://marvelapp.com/9c67ab6/screen/67385098/handoff

Please see the [FP data dictionary](https://docs.google.com/spreadsheets/d/1HZ2l79MBGotLDD_1CcFegHBEgnjgS9qbn9bpBrXgKjA/edit?ts=5e7c5e55#gid=977056555), the following tabs:

Reason for Visit
Vital Signs
Client History
Risk Assessment
Issues & Concerns
Method Selection
Service Provision
Referral

- [x] Reason for visit is the first page of the form. Tapping the X button or the device back button pops up the confirm form close dialog.
-- If user cancels the action, they remain on the form.
-- If user confirms this action, they are sent back to the main register page, or the client's profile page (whichever place they were at before they opened the FP visit form)
- [x] The Next buttons at the top and bottom advance the user to the next section
- [x] The Back button takes the user back to the previous section
- [x] Not pictured, but the last section will have a SAVE button, allowing the user to submit the form once validated.
- [x] Tapping the SAVE button validates the form and takes the user to the updated client profile page.

Marking the issue as blocked until we have the json form conversions for these (in progress, updating the issue below as the jsons are completed).

Json forms by section:
- [Reason for Visit](https://drive.google.com/open?id=1yNLjSfDBP8h1RZsyGUR2uy6ELof7R-zs)
- [Vital Signs](https://drive.google.com/open?id=1keUCHDkB-IEjN1wy5vnX4gtNY-CtVd4b)
- [Client History](https://drive.google.com/open?id=1niBT5wcdFbyCYL9rb1_XuNg2dh_dCBRi)
- [Risk Assessment](https://drive.google.com/open?id=149Vj90sCbDJ6o1S0Asc-aGQTLq34O9ja)
- [Issues & Concerns](https://drive.google.com/open?id=1qMridjPMWQXGRInsGfeFzytzpWkmaX24)
- [Method Selection](https://drive.google.com/open?id=15GawrLO1xnzSmt2wDIxmuZaaPNskjEKS)
- Service Provision
-- [Pregnancy Checklist, Method Removal, Voluntary Consent](https://drive.google.com/open?id=1-eIAmTSkbONm0JpwMR5W2kw3tjjVrGKQ)
-- [Exams & Tests, Method at Exit](https://drive.google.com/open?id=1B1yWeaN-IszES9wEyuH0pKscR5yQMKiE)
- [Referral](https://drive.google.com/open?id=1xL7rzAmPNIomPrXMPwNBaf1jdliDTbCn)

**Comment by dubdabasoduba** [comment]
The form will require a couple of edits even after the generation using the xlson library. Some of the calculation and relevance logic can be copied from the `physical exam` section. @cafootitt Not sure what the [last step](https://marvelapp.com/9c67ab6/screen/67385098/handoff) needs to display.

**Comment by cafootitt** [comment]
@dubdabasoduba Thanks for the feedback. The last step (Roger didn't provide a mockup for this) will be similar to the last page of an ANC form, i.e. the save button will look like this:

![Screenshot_20200407-111510_WHO ANC](https://user-images.githubusercontent.com/3488986/78657779-2f8ccf80-78c1-11ea-8646-4d0298dbebcc.jpg)

**Comment by cafootitt** [comment]
@syedowaisali90 I just have service provision left to do. I'll complete this by EOD tomorrow (Friday). Please go ahead and start on the other jsons in the meantime, if you need to move on to a new issue before the end of the week.

**Comment by owais-vd** [comment]
Hi, @cafootitt has service provision JSON completed.

**Comment by cafootitt** [comment]
@syedowaisali90 Unfortunately, not yet. I'm getting to it today. I was called to help out on a proposal on Friday and Monday and didn't get a chance. I'll post it here as soon as it's complete.

**Comment by cafootitt** [comment]
QA 29 April build:

### Reason for Visit
- [x] Visit date does not have red asterisk denoting it is a required field.
- [x] I cannot enter earlier dates for the visit date. If I try to select an earlier date, it reverts back to today's date.
- [x] The date field is a bit different from the date fields we normally see the native form library. I'm wondering what the reason for this is, and if we can make the date fields look like the ones found in the ANC app (below is a side by side look at a date field in the ANC app (left) vs. date field in the FP app (right))
- [x] The pregnancy intention question should only appear for females, but right now it's appearing when I open a FP visit for males as well.
![Screen_Shot_2020-04-29_at_4_58_22_PM](https://user-images.githubusercontent.com/3488986/80618184-e69ce680-8a3a-11ea-8245-ca0191e02a1b.jpg)


CF: QA 6 May build - all issues above are addressed. Reason for visit passes QA.

**Comment by cafootitt** [comment]
QA 29 April build:

### Vital Signs
- [x] "gender = female" logic is not working for this entire section. Please refer to data dictionary for the logic.
- [x] Upper constraint on body weight should reference 400, not 250.
- [x] BMI note does not display the BMI, even after height and weight are entered. It still shows as "false" value.
- [x] Please adjust the "Blood pressure cannot be taken" checkbox font size. It should be similar to what we see in the ANC app. See below.

<img width="636" alt="Screen Shot 2020-05-04 at 11 40 19 AM" src="https://user-images.githubusercontent.com/3488986/80957930-0bf37100-8dfc-11ea-8302-d79fbba83486.png">


QA 6 May build - lgtm - all issues above are addressed. Good work!

**Comment by cafootitt** [comment]
QA 6 May build:

### Client History
- [x] I don't think the method at intake field is using the method_gender_type in the relevance, because I registered a person where gender = other, and biological sex = female. For this person, method_gender_type should be Female, but in Client History, method at intake is not appearing. To replicate, register a person with gender = other and biological sex = female and then start a FP visit.
- [x] Other (Specify) field in row 95 in data dictionary is not working. It should appear if you check "Other (Specify)" as a reason for no contraceptive method at intake.
- [x] Missing constraint logic on date field for the following date fields: 
iud_insertion_date
implant_date
last_injection_date
sterilization_date
- [x] Constraint missing on the parity field: <= {gravida}
- [x] Constraint missing on the delivery_date field


CF: QA 14 May build - all issues above are addressed. Client History passes QA.

**Comment by cafootitt** [comment]
QA 29 April build:

### Risk Assessment
- [x] "STI risk factors" label is missing from the sti_risk_factors field. I only see the answer choices right now.
- [x] "Risk factors for intimate partner violence or sexual assault" label is missing from the gbv_risk_factors field. I only see the answer choices right now.

QA 6 May build - lgtm, all issues above addressed, good work!

**Comment by cafootitt** [comment]
QA 29 April build:

### Issues & Concerns

- [x] Unable to QA because relevance logic for the first question is not working: selected({reason_for_visit}, "Issues and concerns" AND {method_gender_type} = "Male" and selected({reason_for_visit}, "Issues and concerns" AND {method_gender_type} = "Female"

QA 6 May build - lgtm, all issues above addressed, good work!

**Comment by cafootitt** [comment]
QA 29 April build:

### Method Selection
- [x] Unable to QA this page completely due to {current_method} logic missing.
- [x] "Medical Eligibility Criteria (MEC)" should be a button that opens the MEC app.

QA 6 May build:
- [x] Relevance logic on method_chosen field is missing.

CF: QA 14 May build - all issues above are addressed. Method Selection passes QA.

**Comment by cafootitt** [comment]
QA 6 May build:

### Service Provision
- [x] For reason_different_chosen_exit_method, we may need to update the logic, so that if chosen_method is null (because the field wasn't relevant), then the reason_different_chosen_exit_method field should not be relevant either.
- [x] pregnancy_not_ruled_out_note and informed_consent_note should be yellow notes, not red notes.
- [x] Under Exams & Tests, the info icons on the counseling notes are missing. Please refer to the info icon column for rows 46-51 in the data dictionary.

CF: QA 14 May build - all issues above are addressed. Service Provision passes QA.

**Comment by cafootitt** [comment]
QA 6 May build:

### Referral
- [x] referral_reason should be select multiple; right now it's select one.
- [x] referral_notes field is missing
- [x] Filling in the FP visit form for a male, I put method at intake is male condoms, then on method selection, I put continue method, and method will be provided on site. In this situation, the Referral page should not be relevant, but right now, it's showing and one is able to fill it out.

CF: QA 14 May build - all issues above are addressed. Referral passes QA.

**Comment by owais-vd** [comment]
> QA 6 May build:
> 
> * [ ]  Relevance logic on method_chosen field is missing.
> * [ ]

Actually this is a calculated (hidden) field like if `method_chosen = global_method_gender_type == 'female' ? method_chosen_f : method_chosen_m`

Please elaborate a bit more if I wrong to get understand this point.

@syedowaisali90 It was my mistake. I meant to say the relevance logic on the provide_method_location field seems to be missing, as the question is appearing all the time, so the relevance logic of {method_chosen} != "No method" might be missing.

**Comment by owais-vd** [comment]
> QA 6 May build:
> 
> ### Client History
> * [ ]  I don't think the method at intake field is using the method_gender_type in the relevance, because I registered a person where gender = other, and biological sex = female. For this person, method_gender_type should be Female, but in Client History, method at intake is not appearing. To replicate, register a person with gender = other and biological sex = female and then start a FP visit.

This is has happened because of `method_gender_type` was not properly added in the database. I had informed @zzainulabidin and he has fixed that issue so once he pushes the change in the master branch then it will work properly.

**Comment by owais-vd** [comment]
> QA 6 May build:
> 
> ### Referral
> * [ ]  Filling in the FP visit form for a male, I put method at intake is male condoms, then on method selection, I put continue method, and method will be provided on site. In this situation, the Referral page should not be relevant, but right now, it's showing and one is able to fill it out.

According to the data dictionary. All the referral fields will be relevant if the `referral == yes` that's why i did it and referral check comes from database in `ec_client` table

@syedowaisali90 I tested this more, and I think the issue is that if you go back and edit your selection, the referral logic is not updated. 

For example, if I register a new male client and his chosen method is male condoms and I originally put method provided on site, then it correctly does not show the referral page questions; however, if I go back and change that selection to provided off site, then the referral logic is not updated and the questions on the referral page are still not shown.

**Comment by owais-vd** [comment]
> > QA 6 May build:
> > ### Referral
> > 
> > * [ ]   Filling in the FP visit form for a male, I put method at intake is male condoms, then on method selection, I put continue method, and method will be provided on site. In this situation, the Referral page should not be relevant, but right now, it's showing and one is able to fill it out.
> 
> According to the data dictionary. All the referral fields will be relevant if the `referral == yes` that's why i did it and referral check comes from database in `ec_client` table
> 
> @syedowaisali90 I tested this more, and I think the issue is that if you go back and edit your selection, the referral logic is not updated.
> 
> For example, if I register a new male client and his chosen method is male condoms and I originally put method provided on site, then it correctly does not show the referral page questions; however, if I go back and change that selection to provided off site, then the referral logic is not updated and the questions on the referral page are still not shown.

You mean the referral page will be shown only if a selection is `provide_off_site` and `done_off_site` in both gender types.

**Comment by cafootitt** [comment]
14 May build - this passes QA. Excellent work!
