### ISSUE TITLE
Create client registration form

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-fp#3]
Please see the [data dictionary](https://docs.google.com/spreadsheets/d/1HZ2l79MBGotLDD_1CcFegHBEgnjgS9qbn9bpBrXgKjA/edit#gid=1842326653), Registration tab, for the content specifications of this form.

Marvel handoff: https://marvelapp.com/9c67ab6/screen/64574809/handoff

- [x] This form opens when the user taps on the Register button from the main register page
- [x] Tapping the X button or the device back button pops up the confirm form close dialog. 
-- If user cancels the action, they remain on the registration form.
-- If user confirms this action, they are sent back to the main register page.
- [x] `client_id` field should pre-populate the next available unique 7-digit OpenSRP ID from the ID batch on the device
- [x] Title of the form can be "Client Registration"
- [ ] SAVE button at the bottom and top right remain greyed out until all required fields in the form are filled in at a minimum.
- [x] Tapping the SAVE button validates the form and takes the user to the newly-created profile page of the person they just registered.
- [x] These are the links to the [xlsform](https://drive.google.com/open?id=1y08n66VfCdN1_1-YO1DeWj_xKOn0Cd72) and the [json](https://drive.google.com/open?id=14tor8woFdM92Uz0QJyBnNNwrfGC5Zh-q) forms created from the xlson library. If you see the fields highlighted in dark orange in the [data dictionary](https://docs.google.com/spreadsheets/d/1HZ2l79MBGotLDD_1CcFegHBEgnjgS9qbn9bpBrXgKjA/edit#gid=1842326653) - these are the fields that are not supported in the xlson library, so they need to be manually added or modified in the json.

**Comment by cafootitt** [comment]
Removed the blocked label, as I've added the json form link to the issue above.

**Comment by dubdabasoduba** [comment]
![Screenshot from 2020-04-16 10-46-10](https://user-images.githubusercontent.com/4817531/79429155-d531f400-7fcf-11ea-85e9-f43caddce409.png)
  ```
{
    "key": "anc_id",
    "openmrs_entity_parent": "",
    "openmrs_entity": "person_identifier",
    "openmrs_entity_id": "ANC_ID",
    "type": "barcode",
    "barcode_type": "qrcode",
    "hint": "The ANC client id ",
    "value": "0",
    "scanButtonText": "Scan QR Code",
    "v_numeric": {
      "value": "true",
      "err": "Should be a number"
    },
    "v_required": {
      "value": "true",
      "err": "The anc id is required"
    }
  },
  {
    "key": "anc_id_toaster",
    "openmrs_entity_parent": "",
    "openmrs_entity": "",
    "openmrs_entity_id": "",
    "type": "toaster_notes",
    "text": "The Client id is {client_id}",
    "toaster_type": "info",
    "text_color": "#1199F9",
    "calculation": {
      "rules-engine": {
        "ex-rules": {
          "rules-file": "registration_calculation_rules.yml"
        }
      }
    }
  }
```
Add this piece of code to the `registration_calculation_rules.yml` file. If you don't have the file please create it in the `assets > rule` folder.
```
---
name: step1_anc_id_toaster
description: Note displaying the client id
priority: 1
condition: "true"
actions:
  - "calculation = ['client_id' : step1_anc_id]"
```

**Comment by cafootitt** [comment]
QA 29 April build: Lgtm, good work!
