### ISSUE TITLE
Create main register page

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-fp#5]
Marvel handoff: https://marvelapp.com/9c67ab6/screen/67385096/handoff

- [x] User lands on this page after successful login and anytime they tap on the Clients button in the bottom navigation menu
-- Clients button should be highlighted in blue color when the user is on this page
- [x] Search bar should say "Search name or ID" instead of "Search clients"
- [x] Clients are sorted by last updated. Updated is defined as any of the following:
-- Client was just registered
-- Client's registration form was just edited
-- Client was just called
-- Client just had a FP visit
- [x] Client details are filled in, as per below:

![Screen_Shot_2020-03-25_at_4_50_22_PM](https://user-images.githubusercontent.com/3488986/77563857-bdc48700-6eb9-11ea-98dd-3f0d244a1637.jpg)

**Comment by cafootitt** [comment]
@syedowaisali90 Slight change here to note. Please change the button label from "MEC Wheel" to just "MEC"

**Comment by zzainulabidin** [comment]
Accidentally clicked on close issue, I am reopening this issue.

**Comment by cafootitt** [comment]
QA 29 April build: lgtm, good job!
