### ISSUE TITLE
Update the FP Registration Form and Stop/Change form FP method choices

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-fp#54]
- [ ] Update the FP Registration and Stop/Change FP method for the COC and POP choice options. Basically, we would want the following to be:
FP Registration
- If COC_POP = 1, then COC and POP would appear in the choice options for fp_method_chw
- If COC_POP = 0 and POP = 1, then ONLY POP would appear in the choice options for fp_method_chw.
- If COC_POP = 0 and POP = 0 and no_pill = 1, then NEITHER POP or COC would appear in the options for fp_method_chw.

Stop/Change FP form
- If COC_POP = 1, then COC and POP would appear in the choice options for fp_method_chosen
- If COC_POP = 0 and POP = 1, then ONLY POP would appear in the choice options for fp_method_chosen.
- If COC_POP = 0 and POP = 0 and no_pill = 1, then NEITHER POP or COC would appear in the options for fp_method_chosen.

NOTE: The data dictionary has not been updated, because I think this may required some work to figure out how we want to do?
Data Dictionary: https://docs.google.com/spreadsheets/d/1xJtrHmKqEVuWjvzAcewEavATrfkw9mN-Okf_zGR544w/edit#gid=698403317

**Comment by cafootitt** [comment]
@msschroeder Can you move this to the CHW FP repo please?
