### ISSUE TITLE
Create the link to the MEC wheel app

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-fp#6]
- [x] When the user taps on the "MEC" icon in the main register page bottom navigation, the user is directed to the MEC app, if installed on the device.
- [x] If the MEC app is not installed on the device, the user is directed to the Play Store page for the MEC app to install it: https://play.google.com/store/apps/details?id=com.who.mecwheel

**Comment by dubdabasoduba** [comment]
@cafootitt  Not sure if this addresses the send on the selections on our forms to the MEC wheel app so for now I will give it the largest story points until we are done scoping that piece and create more descriptive issues for the task.

**Comment by cafootitt** [comment]
@dubdabasoduba No, the scope is just to be able to link to the app, there is no requirement to exchange any data. Does that change this to a small t-shirt size?

**Comment by dubdabasoduba** [comment]
Yes then this should be small

**Comment by cafootitt** [comment]
@syedowaisali90 When I tap on the MEC app button on the main register page, it takes me to this error message:

![Screenshot_20200429-164020_Google Play Store](https://user-images.githubusercontent.com/3488986/80616099-62e1fa80-8a38-11ea-843b-e162c3524aad.jpg)

Not sure what this means, because I have play store installed, I also have web browsing apps installed. The expected behavior is that it prompts me to install the MEC app by taking me to the MEC app page in the Play Store. I'm testing on a Samsung Galaxy A10 device.

**Comment by owais-vd** [comment]
@cafootitt I have fixed this one. The reason of this dialog is that because I had forgotten to update the link concatenation when I was converting the code Kotlin to Java.

**Comment by cafootitt** [comment]
QA 6 May build - lgtm, good work!
